name: Deploy Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build:
    uses: ./.github/workflows/build-pipeline.yml

  integration-tests:
    name: Integration Tests (Preâ€‘Deploy)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Run Integration Tests
        working-directory: ./tests/integration-tests
        run: |
          docker compose up --build -d
          docker compose logs -f test-runner &
          docker compose wait test-runner
          exit_code=$(docker compose ps -a --format json \
            | jq -r 'select(.Name == "integration-test-runner") | .ExitCode')
          docker compose down -v
          exit $exit_code

  deploy-scheduler-engine:
    name: Deploy Scheduler Engine
    runs-on: ubuntu-latest
    needs: [build, integration-tests]
    if: needs.build.outputs.scheduler-engine-changed == 'true'
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-2
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python bin/deploy_scheduler_engine.py
  
  deploy-user-service:
    name: Deploy User Service
    runs-on: ubuntu-latest
    needs: [build, integration]
    if: needs.build.outputs.user-service-changed == 'true'
    permissions:
      id-token: write
      contents: read
    env:
       AWS_REGION: us-east-2
       ROLE_ARN: ${{ secrets.ROLE_ARN }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python bin/deploy_user_service.py

  deploy-api:
    name: Deploy API Handlers
    runs-on: ubuntu-latest
    needs: [build, integration-tests]
    if: needs.build.outputs.api-changed == 'true'
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-2
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10.26.1
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          cache-dependency-path: ./api/pnpm-lock.yaml
      - run: pnpm install
        working-directory: ./api
      - run: pnpm run deploy
        working-directory: ./api